merge
alsokolov/praktikum-cards pull request #1
Opened 2020-02-25 19:21 UTC by alsokolov

- add webpack module bundler
- add babel JS plugin
- add plugins for file optimization (CSS, images)
- add dev and production configuration
- mv resourses in ./src dir
- add postCss and babel config files

2020-02-26 16:55 UTC, aarefiev requested changes
Очень хорошая работа. Есть все необходимые ветки (`master`, `develop`, `gh-pages`), проект выложен на Github Pages, открывается, весь функционал на сайте работает. Сайт общается с API по HTTPS. Ридми есть, оформлено, но не достаточно: нет инструкции как развернуть проект. Игнорируются временные файлы. В самой работе используется `webpack`, есть файл `.nojekyll`, настроено хэширование CSS и JS файлов, JS код транспилится в ES5, CSS минифицируется и проставляются префиксы, изображения оптимизируются. При запуске сайта локально все работает, ошибок в консоли нет. Общение с API происходит по протоколу `http`.

Найдена одна ошибка и несколько улучшений. Ниже я указал краткий список, развернутые комментарии будут непосредственно в коде.

**Нужно исправить:** доработать README.md.

**Можно лучше:** 
1. Вынести `targets` в отдельный файл.
2. Добавить оптимизацию для шрифтов.

2020-02-26 16:55 UTC, aarefiev commented on babel.config.js
> +      },
Можно лучше: вынести `targets` в отдельный файл.
Благодаря использованию https://github.com/browserslist/browserslist можно задать единые параметры поддержки для многих инструментов, таких как: `babel`, `autoprefixer` и другие.
Этот инструмент также рекомендуется в документации `babel`: https://babeljs.io/docs/en/babel-preset-env#browserslist-integration .

2020-02-26 16:55 UTC, aarefiev commented on package.json
> +    "build": "cross-env NODE_ENV=production rimraf dist && webpack --mode production",
🦀 Понятно, что этот код был взят как есть из практики, поэтому не отношу его ни к одной из секций. 🦀 

Если залогировать значение `process.env.NODE_ENV` в `webpack.config.js` мы получим следующее:
```bash
$ npm run build

> cross-env NODE_ENV=production rimraf dist && webpack --mode production

{ NODE_ENV: undefined }
```

Это связано с тем, что при выполнении команды `npm run build` будет выполнено 2-е команды последовательно (они соединены через `&&`):
1. `cross-env NODE_ENV=production rimraf dist`.
2. `webpack --mode production`

Видно, что ENV переменная не передается 2-й команде соответственно в коде `process.env.NODE_ENV` равен `undefined`. 

Чтобы работало, нужно `cross-env NODE_ENV=production` перенести во вторую команду:
```suggestion
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --mode production",
```

Результаты выполнения:
```bash
$ npm run build

> cross-env NODE_ENV=production rimraf dist && webpack --mode production

{ NODE_ENV: 'production' }
```

2020-02-26 16:55 UTC, aarefiev commented on webpack.config.js
> +        test: /\.(eot|ttf|woff|woff2)$/,
Можно лучше: добавить оптимизацию для шрифтов.
Подробнее: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru .

2020-02-26 16:55 UTC, aarefiev commented on README.md
> +
Нужно исправить: доработать README.md.
Нужно указать в описании:
- информацию о том, как развернуть проект

В дополнение к ссылкам из практики рекомендую почитать статью "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)". Примеры шаблонов для README:
- https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
- https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-02-27 19:34 UTC, alsokolov commented on babel.config.js
> +      },
Перенес в .browserslistrc

2020-02-27 19:38 UTC, alsokolov commented on webpack.config.js
> +        test: /\.(eot|ttf|woff|woff2)$/,
Добавил woff дополнительно к woff2. Или стоит еще unicode-range добавить?

2020-02-28 13:59 UTC, aarefiev commented on webpack.config.js
> +        test: /\.(eot|ttf|woff|woff2)$/,
По идее их достаточно. Хотя на самом деле всё зависит от требований к поддержке браузеров. Если нужно только современные, то можно даже и меньше шрифтов оставить.

2020-02-28 14:00 UTC, aarefiev approved these changes
Ошибки исправлены, новых не обнаружено.
Отлично, работа принимается :tada: :rocket: .

2020-02-28 19:40 UTC, merged